core:
  location: "eva_datasets"
  sqlalchemy_database_uri: 'mysql+pymysql://root@localhost/eva_catalog'
  application: "eva"

executor:
  batch_size: 50
  gpu_batch_size: 1
  gpus: {'130.207.125.60': [1]}
  cache: "src.cache.no_cache.NoCache"  

storage:
  engine: "src.storage.petastorm_storage_engine.PetastormStorageEngine"

pyspark:
  property: {'spark.logConf': 'true',
             'spark.driver.memory': '1g',
             'spark.sql.execution.arrow.pyspark.enabled': 'true'}

server:
  host: "0.0.0.0"
  port: 5432
  socket_timeout: 60
